### ISSUE TITLE
failed to install imagej-FX

### ISSUE THREAD

**Issue by Fankbai** [cmongis/imagejfx-core#1]
@cmongis 
Hi, it happened something and showed this:
![image](https://user-images.githubusercontent.com/10338671/40523931-722635c4-600a-11e8-8b16-c6ab192c8927.png)

**Comment by Fankbai** [comment]
This site **http://site.imagejfx.net** has nothing.

**Comment by maciejmotyka** [comment]
I experience the same problem.

**Comment by cmongis** [comment]
Thanks for reaching up to me. The update site server was down for some reason. I put it back online :-)
